name: Scala CI

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Unit tests for noMessaging
      run: sbt "project noMessaging; test"
    - name: Unit tests for compiler
      run: sbt "project core; test"
    - name: Unit tests for library
      run: sbt "project library; test"
    - name: Examples compile
      run: sbt "project example; runAll"
    - name: Compiled examples run
      run: sbt "project genExample; testOnly generated.example.test.generatedExamples"
